### ISSUE TITLE
Access a Classic Schema from SAP Business Application Studio

### ISSUE THREAD

**Issue by karpovas1505** [SAPDocuments/Issues#119]
Tutorial: https://developers.sap.com/tutorials/hana-cloud-access-cross-container-schema.html
--------------------------

Hi i have an issue with priviliges when i created schema:
 
Could not execute 'CREATE SCHEMA "PLAIN"'
Error: (dberror) [258]: insufficient privilege: Detailed info for this error can be found with guid 'D06BF788FFAB2B47BEA01BEDAE761BAC'

i see next error if i try to execute troubleshooting procedure:

Could not execute 'call SYS.GET_INSUFFICIENT_PRIVILEGE_ERROR_DETAILS ('6B6E9A641284B84BBDD89866FD3C2816', ?)'
Error: (dberror) [258]: insufficient privilege: Detailed info for this error can be found with guid '9AA485F9B0448F43AD9780D7BC573AFD'

**Comment by jung-thomas** [comment]
From the sound of things you aren't using the right connection in the Database Explorer.  You need to be connected as DBADMIN. Did you use the Open SAP HANA Database Explorer from the Actions column of the HANA Cloud management screen?  This should automatically connect you to the system as DBADMIN.  If you are reusing one of the HDI container instance connections, that user will not have the correct privileges since they are limited to only the security scope of the container.  You need a general admin user to perform this part of the tutorial.
