### ISSUE TITLE
 Create a Simple IoT Device Model

### ISSUE THREAD

**Issue by cabhishekin** [SAPDocuments/Issues#166]
Tutorials: https://developers.sap.com/tutorials/iot-express-2-create-device-model.html
--------------------------
The tutorial is using a simulated environment in step 6 which is not helpful. Instead use a 'real' device such as NodeMCU/ESP8266 operating in constraint environments of libraries, certificate authentications  etc.  Any IoT blog must work with real devices and not on a simulator. Everything works on the simulator but when it comes to working with real devices, real problems are encountered.

**Comment by marcuscbehrens** [comment]
Hi, I agree with you. Data from real sensors also is much more interesting to work with and is always good for surprises - also including surprises coming from gaps in the data or lost data.

We have provided a tutorial with a raspberry pi in the past and this is still relevant and can be used to set-up real hardware. It is available here: https://developers.sap.com/tutorials/iot-express-3-configure-device.html

We do less of the hardware specific part of an end-to-end scenario as due to a strategy shift in the last 2 years we now do not exclusively focus on our own device management anymore, but provide options to leverage device management solutions from partners, and still get the benefit of SAP IoT establishing the business context for the sensor data during ingestion and at rest.

Regards, Marcus Behrens
