### ISSUE TITLE
Set Up Integration Suite Trial

### ISSUE THREAD

**Issue by wikushartzenberg** [SAPDocuments/Issues#189]
Tutorials: https://developers.sap.com/tutorials/cp-starter-isuite-onboard-subscribe.html
--------------------------

Your documentation is out of date and the screenshot and instructions no longer relevant since the systems have been refactored.

**Comment by Karunaharan** [comment]
@wikushartzenberg - thanks for the feedback. Are you referring to the content that mentions about how to subscribe to the service? If yes, we are in the process of publishing the updated content very soon. If no, could you please let me know which part of the tutorial is irrelevant so that I can fix it.

Thanks,
Karuna

**Comment by Karunaharan** [comment]
@wikushartzenberg - tutorials are updated now
