### ISSUE TITLE
Use Machine Learning to Enrich Employee Data with Swagger UI

### ISSUE THREAD

**Issue by advit-ramesh** [SAPDocuments/Issues#190]
Tutorials: https://developers.sap.com/tutorials/cp-aibus-dox-data-api-emp.html
--------------------------

Hello Experts,

I am having trouble with POST /document/jobs. I get

 {
  "error": {
    "code": "E102",
    "message": "Request exceeds trial account quotas.",
    "details": []
  }
}

Do I need to delete the instance on the trial account and provision it again from the booster?

I have checked if there are any existing document job for the client by invoking GET /document/jobs
I get the result below 
{
  "results": []
}

Can you please advise. 

Thanks 
Regards
Advit

**Comment by Juliana-Morais** [comment]
Hi Advit,

Please observe the Trial Account Input Limits (https://help.sap.com/viewer/5fa7265b9ff64d73bac7cec61ee55ae6/SHIP/en-US/44c9f41e36544ad0acf8796665668c96.html).

Best regards,
Juliana

**Comment by Juliana-Morais** [comment]
Hi Advit,

I've just heard we had an issue with our trial limits that has already been fixed.

We have done a root cause analysis. We found the issue which has been related to a fix that we have recently delivered. Now, it should work for a newly created trial account. Hence, I would like to ask you to create a new trial account and try it again. Thank you for providing feedback. We hope it will work again.

Best regards,
Juliana
