### ISSUE TITLE
Create a Basic Workflow in SAP Business Application Studio

### ISSUE THREAD

**Issue by thhapke** [SAPDocuments/Issues#193]
Tutorials: https://developers.sap.com/tutorials/cp-workflow-2-create-module-cf.html
--------------------------

I followed the instructions. After creating with YEOMAN a workflow and having given id,name,description etc the canvas opens without start and end task and the canvas at the left side compains no data given. If I add again the data I still cannot add any blocks to the canvas. 

Thanks, 

Thorsten

**Comment by AstridHerbst** [comment]
Hi Thorsten, 

Unfortunately, this is a know bug that is being worked on. Have you loaded the HANA Calc View Editor together with Workflow Management extension, then... 
o	... the Workflow and Step Editor opens “blank”
o	... the Variant Editor does not allow dragging of steps
Current Workaround:
•	Use separate dev spaces for HANA Calc View Editor and Workflow Management extension (and do not run them in the same dev space)

Is this of help?
Best regards, Astrid

**Comment by thecodester** [comment]
@thhapke Thank you for your feedback. We haven't heard from you in a while, so we are closing the issue.  If you still have questions, feel free to reopen the issue.

@AstridHerbst Is this something for which we should add a note, or otherwise update the tutorial. If the tutorial is fine, please close the ticket.
