### ISSUE TITLE
Use Machine Learning to Extract Information from Documents with Document Information Extraction Trial UI

### ISSUE THREAD

**Issue by masahiroo** [SAPDocuments/Issues#194]
Tutorials: https://developers.sap.com/tutorials/cp-aibus-dox-ui.html
--------------------------

Hello experts,

I am having trouble with uploading another document just after upload documents.  I get

Upload Status:
Error - Request exceeds trial account quotas. (Code: E102)

I did not create any client other than 'default' and so I think the number of clientIds does not exceed the limit 1.

Best regards,
Masahiro Obata

**Comment by Juliana-Morais** [comment]
Hi Masahiro,

Please observe the Trial Account Input Limits (https://help.sap.com/viewer/5fa7265b9ff64d73bac7cec61ee55ae6/SHIP/en-US/44c9f41e36544ad0acf8796665668c96.html). You can only upload 40 document pages per week using a Trial account.

Best regards,
Juliana

**Comment by Juliana-Morais** [comment]
Hi Masahiro,

I've just heard we had an issue with our trial limits that has already been fixed.

We have done a root cause analysis. We found the issue which has been related to a fix that we have recently delivered. Now, it should work for a newly created trial account. Hence, I would like to ask you to create a new trial account and try it again. Thank you for providing feedback. We hope it will work again.

Best regards,
Juliana
