### ISSUE TITLE
 Enable SAP Cloud Platform Internet of Things for Cloud Foundry

### ISSUE THREAD

**Issue by amitavamitra** [SAPDocuments/Issues#221]
Tutorials: https://developers.sap.com/tutorials/iot-cf-enable-iot-service.html
--------------------------

Write here what you need help with ...

Question : Does this tutorial work anymore as I am greeted with completely different screens.

Step 1: Create a Service Instance

![image](https://user-images.githubusercontent.com/20745562/110675369-b5e51c00-81ca-11eb-8555-061adda39813.png)

further more when I search for Internet of Things I see quite a few options.

![image](https://user-images.githubusercontent.com/20745562/110675574-f04eb900-81ca-11eb-88b1-242b24714e76.png)

If this tutorial is not relevant might be useful to take it down or revise the same.

Kind Regards 

Amitava

**Comment by iwonahahn** [comment]
@MichaelCzcz the tutorials are outdated and also SAP CP is mentioned instead of SAP BTP. I will contact @SupriyaCherukunnathu via email asking if the tutorials are still relevant cause I handed them over 2 years ago and they were never updated so far. I feel responsible here to clarify this cause I was named as the author in all 10 IoT tutorials.

**Comment by iwonahahn** [comment]
All tutorials will be reviewed and the colleagues will get back here asap.

**Comment by SupriyaCherukunnathu** [comment]
@MichaelCzcz, we are awaiting confirmation regarding updating or removing this tutorial, will update here based on the final decision.

**Comment by iwonahahn** [comment]
see email thread with @marcuscbehrens

**Comment by SupriyaCherukunnathu** [comment]
@MichaelCzcz, please note that this tutorial is removed, hence closing this issue.
