### ISSUE TITLE
Create Database Artifacts Using Core Data Services (CDS) for SAP HANA Cloud

### ISSUE THREAD

**Issue by mts2605** [SAPDocuments/Issues#259]
Tutorials: https://developers.sap.com/tutorials/hana-cloud-cap-create-database-cds.html
--------------------------

Step 3 - Ad 6
I get error:
Could not create the Failed to open connection to the database, because of: Failed to get connection for database '0e130c00-1687-494c-8f07-72bc42ca6bf9' (0e130c00-1687-494c-8f07-72bc42ca6bf9.hana.trial-eu10.hanacloud.ondemand.com:443), because of: SAP DBTech JDBC: Cannot connect to jdbc:sap://0e130c00-1687-494c-8f07-72bc42ca6bf9.hana.trial-eu10.hanacloud.ondemand.com:443 [Object is closed: com.sap.db.jdbc.SecureChannelSession@6ce798f 0e130c00-1687-494c-8f07-72bc42ca6bf9.hana.trial-eu10.hanacloud.ondemand.com:443 ConnectionID:0 SessionID:0 on sun.nio.ch.UnixAsynchronousSocketChannelImpl[connected local=/10.136.185.27:45066 remote=0e130c00-1687-494c-8f07-72bc42ca6bf9.hana.trial-eu10.hanacloud.ondemand.com/18.157.215.35:443]]. entity, consider deleting it using the 'cf delete-service MyHANAApp-hdiMyHANAApp-db-deployer-ws-6mx7m command'

**Comment by jung-thomas** [comment]
Is your HANA Cloud instance running and reachable?  This error would seem to indicate that it can not be connect to. Remember that HANA Cloud trial shuts down every night and has to manually be restarted every day.

**Comment by mts2605** [comment]
@jung-thomas Thanks for replying. There was a problem with the instance. It was deleted, a new created. (Is it normal that it takes more than 3 hours for a trial-acc.?)
Case closed. 
FYI - really appreciate the work done with all these tutorials!

**Comment by jung-thomas** [comment]
There have been some general issues with the HANA Cloud trial infrastructure in the last day.  I personally had an instance that was in the starting status for over 12 hours.  However support was alerted to the issue yesterday and has been working on it since.  I know that my instance is back and working good and so are some of the other trial instance by other members of my team. So I think they are close to resolving the issue overall.  But short answer - no it doesn't normal take 3 hours for a trial instance creation. More like 10-15 minutes tops for instance creation and then only about 2-3 minutes for system restart under normal circumstances.
