### ISSUE TITLE
Add User Authentication to Your Application (SAP HANA Cloud)

### ISSUE THREAD

**Issue by mts2605** [SAPDocuments/Issues#266]
Tutorials: https://developers.sap.com/tutorials/hana-cloud-cap-add-authentication.html
--------------------------

pre-step 1 - link to ( User Account and Authentication Services - UAA) = 
https://help.sap.com/viewer/65de2977205c403bbc107264b8eccf4b/Cloud/en-US/51ec15a8979e497fbcaadf80da9b63ba.html11

Sorry, we can't find the page you're looking for...

;-)

**Comment by jung-thomas** [comment]
Sorry about that.  Looks like the page in the documentation we had linked to may no longer exist. Perhaps due to some restructuring.  However I've updated the tutorial with the new link and it should be present in the production system in a few minutes. Her also is the new link: https://help.sap.com/viewer/65de2977205c403bbc107264b8eccf4b/Cloud/en-US/649961f8d4ad463daca33b3a20deba4c.html
