### ISSUE TITLE
Create Database Artifacts Using Core Data Services (CDS) for SAP HANA Cloud

### ISSUE THREAD

**Issue by rvinod14** [SAPDocuments/Issues#268]
Tutorials: https://developers.sap.com/tutorials/hana-cloud-cap-create-database-cds.html
--------------------------

Hi Experts,
I'm getting error in Step 3: Explore generated design-time artifacts. I'm not able to Bind the project to a Database Connection and HDI container instance.
After clicking the Bind Icon and generating New Service Instance error is occurring.
Below is the error message.
![image](https://user-images.githubusercontent.com/57740183/112430107-b0a7d580-8d63-11eb-9ec7-c30ac91f8c92.png)

Regards,
Vinod Iyer

**Comment by Rollingbasti** [comment]
Hello,

i am getting the same error in Step 1 of the tutorial "Create an SAP HANA Database Project". Every time i want to create a new HANA project with the SAP HANA Database Project template, it is unable to create a hdi-shared Service. 

Error Message is the same as above:
`Failed to open connection to the database, because of: Failed to get connection for database '5609ce11-5df3-4401-ae34-24f7df0e5597' (5609ce11-5df3-4401-ae34-24f7df0e5597.hana.trial-eu10.hanacloud.ondemand.com:443), because of: SAP DBTech JDBC: Cannot connect to jdbc:sap://5609ce11-5df3-4401-ae34-24f7df0e5597.hana.trial-eu10.hanacloud.ondemand.com:443 [Object is closed: com.sap.db.jdbc.SecureChannelSession@233c7441 5609ce11-5df3-4401-ae34-24f7df0e5597.hana.trial-eu10.hanacloud.ondemand.com:443 ConnectionID:0 SessionID:0 on sun.nio.ch.UnixAsynchronousSocketChannelImpl[connected local=/10.142.50.124:41144 remote=5609ce11-5df3-4401-ae34-24f7df0e5597.hana.trial-eu10.hanacloud.ondemand.com/18.157.215.35:443]].`

Kind Regards,

Sebastian

**Comment by jung-thomas** [comment]
Well the error message says that you are unable to connect to your HANA database.  For first question is: Is your HANA system running?  Please check the status from the HANA Cloud page in the BTP Cockpit.  Remember that the HANA Cloud free trial shuts down all instances every night. You must manually restart the database each day you want to use it. Most likely the system isn't running yet because it hasn't been started.  If the HANA Cloud page says the instance is running then also try to connect with the HANA Cockpit from this admin page.  This admin tool will tell you if there is something wrong with the health of your system.

**Comment by Rollingbasti** [comment]
Hello Thomas,

thank you for your quick response. Starting the HANA System from the cockpit, has fixed the error in my case 👍🏼 

Kind regards,

Sebastian

**Comment by rvinod14** [comment]
Hello Thomas,

In my case earlier the HANA Cloud trail instance was running but was not getting connected to HANA_CLOUD_TRIAL database in the SAP HANA Database Explorer.
Now its connecting to the HANA_CLOUD_TRIAL database and also the Binding is happening.

Thanks & Regards,
Vinod Iyer
