### ISSUE TITLE
 Create Data Model and Lock Object in SAP BTP, ABAP Environment

### ISSUE THREAD

**Issue by mts2605** [SAPDocuments/Issues#275]
Tutorials: https://developers.sap.com/tutorials/abap-environment-lock-object.html
--------------------------

In step 6, when/after "Save & activate", i get error.:

Description	Resource	Path	Location	Type
Use of Entity I_BusinessUser is not permitted.	z_i_room_mts.asddls	/TRL_EN/.adt/ddic/ddlsources/z_i_room_mts/z_i_room_mts.asddls	line 9	ABAP Syntax Check Problem

What to do?

**Comment by mervey45** [comment]
Hi @mts2605 ,

did you change the XXX with your own number/character? You have to check, weather it is changed everywhere. You can use therefore CTRL + F and **Search** XXX and add your own number to **Replace With**.
![image](https://user-images.githubusercontent.com/27953324/112994153-3f549200-916a-11eb-844e-4e43a24d95b5.png)
Check also if you have activated everything so far. Otherwise, please contact me again.

Best regards, 
Merve

**Comment by mervey45** [comment]
Hi @mts2605 ,

Can you try to create a new data definition with a new sql view name?

Best regards, 
Merve

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. We haven't heard from you in a while, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
