### ISSUE TITLE
Create Behavior Definition for Managed Scenario

### ISSUE THREAD

**Issue by willanyong** [SAPDocuments/Issues#276]
Tutorials: https://developers.sap.com/tutorials/abap-environment-behavior.html
--------------------------

Create and delete button is not shown up. I followed every steps. Thanks 

![image](https://user-images.githubusercontent.com/15873099/112787385-014a5780-901e-11eb-93a9-9599c9faa6b4.png)

**Comment by cagooi88** [comment]
I have created #280 as well. Found the root cause due to custom action 'Accept Travel' annotation added at your consumption data definition under field OVERALL_STATUS but your behaviour definition file only has CREATE/UPDATE/DELETE. Either you comment out the FOR_ACTION annotation, or you add the custom action to your behaviour definition file which at the following tutorial (https://developers.sap.com/tutorials/abap-environment-behavior-action.html)

**Comment by mervey45** [comment]
Hi,

there seems to be an issue with the annotation of the overall status. If you comment it out and activate your projection view. Then add it back again and activate it. It works. I will update this tutorial to have a better solution.

Best regards,
Merve

**Comment by thecodester** [comment]
Deleting because of duplicate -- https://github.com/SAPDocuments/Issues/issues/219
