### ISSUE TITLE
 Create Instance of SAP Event Mesh

### ISSUE THREAD

**Issue by devsap1** [SAPDocuments/Issues#295]
Tutorials: https://developers.sap.com/tutorials/cp-enterprisemessaging-instance-create.html
--------------------------
Hello Experts,

I have tried to follow the steps with a trial account. It seems the service instance creation JSON does not accept parameters such as namespace, version etc. It allows creation of service instance creation with rather simple JSON as below 
{
"emname": "embus1",
"options": {
    "management": true,
    "messagingrest": true,
    "messaging": true
}
}
With this JSON i could create the instance, but noticed that the message client is not created on the Event mesh application.
The screen looks as below 

![image](https://user-images.githubusercontent.com/82133673/113967900-a0a5f080-984f-11eb-96ee-f5bd20556b82.png)

If i switch to dev plan UI, it rather offers limited options such as channel group

![image](https://user-images.githubusercontent.com/82133673/113968012-dd71e780-984f-11eb-97ad-a87e502ac08b.png)

I believe messaging capabilities cant be used without the message instance being created right ? So is this supported in trial account or is there way to overcome the above issues ?

Any inputs is really helpful

Rgds

**Comment by pradeeppanda-sap** [comment]
Hi,
 Default version of Event Mesh is not available in the trial environment.
 Hence, the json with namespace does not work. And that's why we have mentioned in the tutorial that license is required to be able to follow the tutorial.
![image](https://user-images.githubusercontent.com/51952722/113996142-829eb700-9874-11eb-8587-f9ca4a3f11b4.png)
And that is the reason for which even the management screen (which displays the instance ) does not have any instance.

Of course, to understand the concept of messaging, you can still go ahead with the dev plan (in case you have to use the trial environment). Though the management screen and how to create queues and all are not going to be exactly the same, you will still be able to get a feel of overall event mesh.
Having said that, if you have access to productive system, you can try with that. It will have default plan available for you to be able to follow the tutorial step by step.
regards
Pradeep

**Comment by devsap1** [comment]
Thanks Pradeep for the reply. Its clear for me that, the steps(in the tutorial) as such are relevant for a productive system. Can you help to understand if the event mesh feature can only be then used in productive environment. In the trial account is there a way to consume the events raised from an S4 system ? If you are aware of blogs / help documentation explaining how to consume messages with trial account it will be really helpful.

Thanks again

**Comment by pradeeppanda-sap** [comment]
You can follow [this blog](https://blogs.sap.com/2018/12/18/sap-cloud-platform-enterprise-messaging-making-s4hana-event-notification-easy/#) . Though it is meant for default plan, still you can go ahead with dev and try it out.
Should you have any issue, please let me know.
