### ISSUE TITLE
Add a Custom Event Handler

### ISSUE THREAD

**Issue by EnjoyM2012** [SAPDocuments/Issues#341]
Tutorials: https://developers.sap.com/tutorials/cp-cap-java-custom-handler.html
--------------------------

Would you please confirm that there is not any response in the terminal command line after the “curl -x POST…” run ? I just want to check if my this step goes wrong…
Because I have not got the created record on the command line, either on the new tab app welcome page. I am afraid I have not created this record
 
https://developers.sap.com/tutorials/cp-cap-java-custom-handler.html

![1](https://user-images.githubusercontent.com/31377562/116497384-cb78e700-a8d9-11eb-9521-42d0848c051a.jpg)
![2](https://user-images.githubusercontent.com/31377562/116497400-d764a900-a8d9-11eb-9414-b881f6507a14.jpg)
![3](https://user-images.githubusercontent.com/31377562/116497403-d895d600-a8d9-11eb-932f-0065028a1599.jpg)
![4](https://user-images.githubusercontent.com/31377562/116497405-d92e6c80-a8d9-11eb-9ca7-61a4070b23d7.png)

**Comment by beckermarc** [comment]
Hi @EnjoyM2012,

you should be seeing data on the Products API after running the curl commands. From your screenshot it looks like you pasted the curl commands in the terminal window that is running the Java process. Due to that these commands are not executed correctly. Please execute them in a dedicated separate terminal window.

Best regards,
Marc

**Comment by iwonahahn** [comment]
Hi @EnjoyM2012,

We haven't heard from you in a while, so we are closing the issue.
If you still have questions, feel free to reopen the issue. 

Best regards,
Iwona
