### ISSUE TITLE
Connect SAP Continuous Integration and Delivery with Your Corporate Git

### ISSUE THREAD

**Issue by vanita57** [SAPDocuments/Issues#373]
Tutorials: https://developers.sap.com/tutorials/cicd-corporate-git.html
--------------------------

Hi Team,

For my scenario  I have used our corporate GitHub but I am facing below issue in my build log 

ERROR: Error cloning remote repo 'origin'
[2021-05-12T12:45:03.167Z] hudson.plugins.git.GitException: Command "git fetch --tags --force --progress -- https://github.xxx.xxx.xxxx/I000000/SAPCICD.git +refs/heads/*:refs/remotes/origin/*" returned status code 128:
[2021-05-12T12:45:03.181Z] stdout: 
[2021-05-12T12:45:03.196Z] stderr: fatal: unable to access 'https://github.xxx.xxx.xxxx/I000000/SAPCICD.git/': Received HTTP code 405 from proxy after CONNECT
[2021-05-12T12:45:03.304Z] 
[2021-05-12T12:45:03.317Z]     at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:2450)
[2021-05-12T12:45:03.467Z]     at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandWithCredentials(CliGitAPIImpl.java:2051)

Please help here ?

Regards ,
Vanita

**Comment by MichaelCzcz** [comment]
@vanita57 Never ever post personal information in a public space!

**Comment by romanisb** [comment]
Hi @vanita57,

based on the log snippet it seems that you do not have properly set up you SAP Cloud Connector.

In order to follow the tutorial to use corporate Github repositories with the SAP CICD Service, you must have a SAP Cloud Connector installed, which resides **within your network** and **can reach** your corporate Github.

Please make sure that these requirements are given to properly continue setting up a connection between the Cloud Connector and your BTP Subaccount, as described in **_Step 2_** of the tutorial, and set up a system mapping to your cooperate Github repository, as described in **_Step 3_** of the tutorial.

Best regards

Roman

**Comment by vanita57** [comment]
Hi Roman,

Thank you for your input ,I am able to resolve the issue.
and Even though it is a public repo I used GitHub token credential then it started cloning my repo .
screenshot attached 
![image](https://user-images.githubusercontent.com/56148375/118755618-d4305d80-b886-11eb-9c7f-ea42193f3cbc.png)


Regards,
Vanita

**Comment by romanisb** [comment]
Hi @vanita57

> Thank you for your input ,I am able to resolve the issue.

Sure. You're welcome. I assume that we can close this GH issue then, right?

> and Even though it is a public repo I used GitHub token credential then it started cloning my repo .
> screenshot attached

Hmm, yes. That one is a bit tricky. You're corporate Github provider most-likely disallowed anonymous cloning. In that case credentials are needed although your repository is public. I will propose a change in the tutorial accordingly.


Best regards

Roman

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. We haven't heard from you in a while, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
