### ISSUE TITLE
Matcher is not supported! Matcher name: 'I18NText'

### ISSUE THREAD

**Issue by ncastagno-tgv** [SAPDocuments/Issues#381]
Tutorials: https://developers.sap.com/tutorials/cp-cicd-sytem-test.html
--------------------------

The problem is in step 5.20:
controlType: 'sap.m.Button',
I18NText: {
   propertyName: "text",
   key: "addToCartShort"
}
Execution fails with this error:
javascript error: Matcher is not supported! Matcher name: 'I18NText', arguments: '{"propertyName": "text", "key": "addToCartShort"}' Error: Matcher is not supported! Matcher name: 'I18NText', arguments: '{"propertyName": "text", "key": "addToCartShort"}'
     at https://sapui5.hana.ondemand.com/resources/sap/ui/test/matchers/MatcherFactory.js:6:1216

I do not see differences between what step 5.19 shows and what I see in the UI5 Inspector of my Chrome. 
![2021-05-20 10_11_22-Shopping Cart](https://user-images.githubusercontent.com/62354561/118984369-d1e80500-b953-11eb-8bcb-dfdb7f490cb6.png)

**Comment by ncastagno-tgv** [comment]
Hello Michael
Nothing to comment? 

Regards
Néstor

**Comment by georgbischoff** [comment]
Hi Néstor,

sorry for the delay. You are right, the correct matcher is as follows (with a lowercase i at the beginning):

 ```
 controlType: "sap.m.Button",
  i18NText: {
      propertyName: "text",
      key: "addToCartShort"
  }
```

I further propose to use the tutorial that uses the Test Recorder instead of the UI5 Inspector: https://developers.sap.com/de/tutorials/cp-cicd-systemtest-recorder.html

Let me know if you have further questions.

Regards,
Georg Bischoff

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. We haven't heard from you in a while, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
