### ISSUE TITLE
Add Views and Define Routes to Access Them

### ISSUE THREAD

**Issue by ag3silaus** [SAPDocuments/Issues#386]
Tutorials: https://developers.sap.com/tutorials/sapui5-101-add-routing.html
--------------------------

Hello when i try to open my Preview i'm getting this error. 
ui5loader-dbg.js:1297 GET https://workspaces-ws-f8xnz-app2.eu10.trial.applicationstudio.cloud.sap/resources/sap/btp/sapui5/controller/List.controller.js net::ERR_ABORTED 404
Could you tell me please why i am getting this error. Thank you for your answer.

**Comment by cjbernal** [comment]
Hi there,

Just for clarification, you're seeing this issue on the very last step? "Step 5: Test it"? 

Kind regards,
Conrad

**Comment by ag3silaus** [comment]
Hello Conrad,
Yes, i am getting this issue on last step. 
Kind regards,
Burak

**Comment by cfg74** [comment]
Hi @ag3silaus ,
please apologize for the delay in response. In order to help diagnosing the problem we need the project you are trying to preview. For that, please 1) delete the "node_modules" folder in the project folder, and 2) use "Download" from the right-click menu of your project. 3) Attach the result here for further investigation.

Thanks and best regards,
Christoph

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. We haven't heard from you in a while, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
