### ISSUE TITLE
Automate and Extend Employee Onboarding

### ISSUE THREAD

**Issue by ubabap** [SAPDocuments/Issues#419]
Mission: https://developers.sap.com/mission.cp-starter-ibpm-employeeonboarding.html
--------------------------

Hello together.

Hello together.

I am missing the maybe most central point in this turorial, is that it does never explain, who will see the Items  

So here it is not explained, that you have to add other users to the buddies in the example to enable seeing a collaboration scenario. Also in the sample data , user id's are provided what also might not help for settign up in a trial account.
Maybe simply add a pattern for approver_mail_adress into the sample data to start the Worklflow from simulated event and give a hint to enable a team experience.
(Also there might be issues with the same workflow id used for the simple beginner  onboard and a uploaded onboard Workflow: maybe the tutorial should tell to change the id? )

Also there is no explanation to anything that has been done.
For sure everything is working, but i do not see the learning without having at least hints to the sources, where i can get a little bit of understanding what i am doing when clicking through the tutorial.

**Comment by ArchanaShukla** [comment]
Thanks for you feedback, we will try to improve. The tutorial is not explaining how to create workflow, business rules and therefore it explains on a high level what this scenarios is all about and how to set it up and run it in quick time. If you want to learn the details on these services then you can try out Getting Started tutorials. 

"add other users to the buddies in the example" - this scenario is for trial landscape and it is not advised to add members in trial landscape because it is more for personal trial and PoC purposes. 

"user id's are provided what also might not help for settign up" - they are dummy user Ids just to showcase you how to add multiple users to the user task

"workflow id used for the simple beginner onboard and a uploaded onboard" - yes if you have already the workflow deployed with same name then it will override but you cannot change the workflow ID of the sample once created, and as said in this tutorial we are not teaching to create workflow but to quickly setup workflow and use for references. 

"no explanation to anything that has been done" - the explanation is on the level of Employee Onboarding scenario like what does the workflow do, what does the rule created for etc. If you want to learn more on how-to create then try our getting started tutorials. 

Hope that helps,

**Comment by ubabap** [comment]
Hello Archana,

you might misunderstood , what I was writing.

You do not need to add users and prepare the scenarios but  someone that has his trial account can add another person as a user to his trial account and add the connected email-address to the empData.buddies in the prepared test -json.

I think, it would be worth to explain that as a later or an optional step in the tutorial.
Only then 2 people can try out something like a usual workflow is made for.

For me to just my own Items in my inbox is pretty useless.
And for me this is the missing link to have the minimal set to get an imagination how a workflow process would work. For me that needs a collaboration of at least two different users.

And this are the 2 getting started "Tutorials" : You can just not learn a lot by simply doing them and it could be improved very easily by explaining, what a user is doing together with just saying what to do to see a result.
At least by linking the steps to a help or a more in depth tutorial or whatever.


Beste Grüße/Best regards
Ulrich Becker

Phone +49 89 3547 182958
