### ISSUE TITLE
Create an ABAP Package

### ISSUE THREAD

**Issue by digiaplo** [SAPDocuments/Issues#451]
Tutorials: https://developers.sap.com/tutorials/abap-dev-create-package.html
--------------------------
After filling in the package name, the next screen requires an Access Key, but when I go to SCCR, there is no option to request a key. 
My user ID is P2004064380, please help.

Thanks!

**Comment by julieplummer20** [comment]
Hi,
Are you using a developer edition. Then usually the issue is that the user did not delete ALL the existing licenses before importing the new one. Please follow the guidelines in:
[Newbies’ Guide: 752 Virtual Box](https://www.sap.com/documents/2018/09/92ffae89-1c7d-0010-87a3-c30de2ffd8ff.html)
or
[Newbies’ Guide: 752 VMWare](https://www.sap.com/documents/2018/09/1cefb289-1c7d-0010-87a3-c30de2ffd8ff.html)
(Search for "License"
If you are not on a developer edition, but on a fully licensed version, please just let me know.
Best wishes,
Julie.

**Comment by digiaplo** [comment]
Hi Julie,
Thank you for your support, I am using SAP NetWeaver AS ABAP 7.52 SP04 on VMWare. 
In the past, It has 2 default licenses, I deleted one and install a new one (it is issued by https://go.support.sap.com/minisap/#/minisap). 
After reading your guide, I deleted all 2 licenses and install the one that I requested, restart the system, the problem is still there. 
Do I need to reinstall the SAP NW?
P/S: I access 2 links that you guide, it said the page is not found.

**Comment by digiaplo** [comment]
Hi Julie,
I reinstalled SAP NetWeaver AS ABAP 7.52 SP04 on VMWare, delete all existing licenses then import the new one. But I meet the issue again.

This is SLICENSE screen.
![image](https://user-images.githubusercontent.com/82439395/123530386-d60dfc00-d723-11eb-9a28-2a52daa38694.png)

This is "Add new package" screen on Eclipse
![image](https://user-images.githubusercontent.com/82439395/123530421-2e44fe00-d724-11eb-80c1-e5d2ca25d736.png)

Please help me!
Thanks.
Khoa.

**Comment by digiaplo** [comment]
Hi Julie,
I reconnect with user "DEVELOPER" and created the package successfully.

Thanks for your support.
Khoa.
