### ISSUE TITLE
Set Up the SAP HANA Cloud Service : cpapp-db-deployer failing 

### ISSUE THREAD

**Issue by ibibhu** [SAPDocuments/Issues#454]
Tutorials: https://developers.sap.com/tutorials/btp-app-hana-cloud-setup.html
--------------------------

Write here how you think we can improve the tutorial ...

While doing cf deploy cpapp_1.0.0.mtar in the later part it's failing 

because of "cpapp-db-deployer "

when I did cds add hana  , then finally the deployment worked.

**Comment by uwe-klinger** [comment]
Hi @ibibhu ,

Thanks for providing this feedback. We will look into the possible use of `cds add hana` to simplify the tutorial. 

Since the tutorial worked for our last test, I wonder what error you faced. Did you add the `deploy-format` section in your `package.json` file?

https://developers.sap.com/tutorials/btp-app-hana-cloud-setup.html#c6f9d27b-d8d0-4e7b-8a8a-e18eaa690094

**Comment by ibibhu** [comment]
Yes I have added the deploy format section ,

Let me re iterate the scenario without "cds add hana", 
then will share you the error logs.

**Comment by uwe-klinger** [comment]
Thanks!

**Comment by iwonahahn** [comment]
The issue seems to be resolved, so I am closing the issue. If you still have questions, feel free to reopen the issue.
