### ISSUE TITLE
Continue Your OData Exploration with EPM

### ISSUE THREAD

**Issue by davidsmith288** [SAPDocuments/Issues#521]
Tutorials: https://developers.sap.com/tutorials/odata-02-exploration-epm.html
--------------------------

Write here how you think we can improve the tutorial ...

The tutorial is not working.

In response to 

https://sapes5.sapdevcenter.com/sap/opu/odata/sap/EPM_REF_APPS_SHOP_SRV/Products('HT-1001')

I get this error message 
<error xmlns="http://schemas.microsoft.com/ado/2007/08/dataservices/metadata">
<code>/IWBEP/CM_MGW_RT/020</code>
<message xml:lang="en">Resource not found for segment 'Product'</message>
<innererror>
<application>
<component_id>BC-SRV-NWD-FRA</component_id>
<service_namespace>/SAP/</service_namespace>
<service_id>EPM_REF_APPS_SHOP_SRV</service_id>
<service_version>0001</service_version>
</application>

This means the rest of the tutorial steps 2, 3, 4 5, cannot be completed because they depend on HT-1001 existing

Please fix the tutorial

**Comment by qmacro** [comment]
Hi @davidsmith288 - there are a couple of things here:

1. if the specific product (HT-1001) cannot be found, you can just pick another one - there's a note to this effect directly after the URL that gives HT-1001 as an example ("_If there isn’t a product entry with this specific ID, you can choose another one - the IDs follow a similar pattern._")
2. there does seem to be a general database issue with the system right now - I've alerted the owners of that system to get that fixed. This will unfortunately impact the ability to work through this tutorial but I hope that this issue will be fixed in the next 24-48 hours. 

Thanks for the heads up!
