### ISSUE TITLE
Build a Single Page Application Using UI5 Web Components for React

### ISSUE THREAD

**Issue by Utkarshk7** [SAPDocuments/Issues#574]
Mission: https://developers.sap.com/mission.react-spa.html
--------------------------

Write here how you think we can improve the tutorial ...
Can you please provide steps to deploy the app onPrem?

**Comment by Lukas742** [comment]
Hi @Utkarshk7 

I don't really see this as part of the tutorial, since there are so many ways to distribute an app. Maybe a separate tutorial on this topic would be helpful, but unfortunately I don't have the capacity to create one at the moment. 

The tutorial is build with standard `create-react-app` so you can take a look at this guide [here](https://create-react-app.dev/docs/deployment). Hope that helps at least a little.

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
