### ISSUE TITLE
Create ABAPDoc Comments in Your Class in ABAP Environment

### ISSUE THREAD

**Issue by LadyMarieLovelace** [SAPDocuments/Issues#576]
Tutorials: https://developers.sap.com/tutorials/abap-environment-create-abapdoc.html
--------------------------

The question is: "Which of the following object types can you link to, specifically using the syntax { @link kind:name }Choose all that apply."

I tried several times "Step 6: Test yourself" with the "Use the ABAP Keyword Documentation for help" here:

https://help.sap.com/doc/abapdocu_cp_index_htm/CLOUD/en-US/abendoccomment.htm#@@ITOC@@ABENDOCCOMMENT_5

In compliance with the ABAP Keyword Documentation I was submitting the answer **Class, Constant, Interface, Method**. I even tried other combinations which might make sense, i.e. **Constant, Method** according to the rules for classes and interfaces.

It's possible that I didn't understand the question and the documentation.

**Comment by thecodester** [comment]
@julieplummer20 Also fix the spacing on the question text -- the entire question text must be on 1 line.

**Comment by julieplummer20** [comment]
Hi,
"Class" is not correct here, because the syntax for CLASS is different: 
"kind cannot and must not be specified for global data types and object types (classes and interfaces). These repository objects are solely addressed by their names. This applies specifically to CDS entities."

I wanted to draw attention to the different syntax. However, there was a typo, which I have now fixed. I apologize for the inconvenience.
The correct answer is : CONSTANT, INTERFACE, METHOD .

Thanks for getting in touch. I will now close the question. If you have any further comments, please get in touch.
BR Julie.
