### ISSUE TITLE
Create Database Artifacts Using Core Data Services (CDS) for SAP HANA Cloud

### ISSUE THREAD

**Issue by GirodFred** [SAPDocuments/Issues#633]
Tutorials: https://developers.sap.com/tutorials/hana-cloud-cap-create-database-cds.html
--------------------------

In step 3, "bind our project to a Database Connection and HDI container instance"  I have an error. 

_Failed to chdir to /theia/browser-app: No such file or directory Error: Binding Service MyHANAApp-hdiMyHANAApp-db-deployer-ws-5wxx5 failed : Service instance MyHANAApp-hdiMyHANAApp-db-deployer-ws-5wxx5 not found: Service instance MyHANAApp-hdiMyHANAApp-db-deployer-ws-5wxx5 failed to be created. Error: Failed to open connection to the database, because of: Failed to get connection for database '4b4f67dc-c45f-4a9b-bb0b-71a39ebe803e' (4b4f67dc-c45f-4a9b-bb0b-71a39ebe803e.hana.trial-eu10.hanacloud.ondemand.com:443), because of: SAP DBTech JDBC: Cannot connect to jdbc:sap://4b4f67dc-c45f-4a9b-bb0b-71a39ebe803e.hana.trial-eu10.hanacloud.ondemand.com:443 [Object is closed:..._ 

I see another topic, the Hana must be started, I could understand it. But ... in my SAP Business Application studio page, I have the two elements : 

- Full Stack Cloud Application
- SAP Hana Native Application. 

And I could start only one of this application. 
"You are allowed a total of 2 dev spaces, with only 1 running at a time"   

Or maybe it is another one ? 
Sorry I am little bit lost, used to work in ECC/ S/4  not cloud environment

Best regards
Fred

**Comment by jung-thomas** [comment]
Based upon that error message it would indicate that your HANA database is not reachable. Usually this is caused by the system not being running or when you created your HANA Cloud system you didn't update the allow list (IP address filtering) for all addresses.  
Most likely its the first case.  Remember that if you are using the free SAP HANA Cloud trial instance, these shut down every night to safe costs. You need to manually restart the system. So have you started your HANA Cloud trail instance?

If you are sure the HANA database is running then go back to the HANA Database and check the allow list setting as described originally in this predecessor tutorial - https://developers.sap.com/tutorials/hana-cloud-deploying.html#a17d2f58-74c6-45cf-b859-5aa83eb5ff47
You need to make sure it is set to Allow All IP Addresses. 

You don't start the HANA Database from the Business Application Studio and the running dev space in Business Application Studio also doesn't have anything to do with the running status of your HANA Database. Return to the BTP Cockpit and the SAP HANA Cloud Central view in the Cockpit to check the status of your HANA Database.
