### ISSUE TITLE
Create a Reusable Service

### ISSUE THREAD

**Issue by sdyajian** [SAPDocuments/Issues#80]
Tutorial: https://developers.sap.com/tutorials/cp-cap-java-reusable-service.html
--------------------------

in step5:
5.1 npm install --save-dev sqlite3
the current default node version will fail the npm install process.
fixing via downgrading the npm version to lts version,
- nvm install v8.11.3
- nvm alias default 8.11.3
- restart terminal, and run 'yarn install'
after that the npm install process will be done successfully.

5.2 cds delpy --to sqlite
it fails at ' Cannot find module 'sqlite3'.
Fixing that via below two commands,
- npm install 
- unset NODE_PATH
after that, it works to deploy sqlite.db.

**Comment by iwonahahn** [comment]
Hi @sdyajian,
Thank you for your suggestion. If people report this issue, we always point to the provided solution [here](https://github.com/SAPDocuments/Tutorials/issues/6240#issuecomment-734740827). This issue will be fixed by the SAP Business Application colleagues. So we can close this issue here (@MichaelCzcz).
Best regards,
Iwona
